version: "3"
services:
  app:
    build: .
    command: python login_startcharging.py
    network_mode: host
    ports:
      - "5000:5000"
    volumes:
      - .:/ladeinorge-selenium
    depends_on:
      - chrome
      - selenium-hub
    restart: always

  chrome:
    image: selenium/node-chrome:4.0.0-rc-1-prerelease-20210618
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - DBUS_SESSION_BUS_ADDRESS=/dev/null
    network_mode: host
    ports:
      - "6900:5900"
      - "8900:7900"
    volumes:
      - /dev/shm:/dev/shm
    restart: always

  selenium-hub:
    image: selenium/hub:4.0.0-rc-1-prerelease-20210618
    container_name: selenium-hub
    network_mode: host
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    restart: always